// Generated by CoffeeScript 1.7.1
(function() {
  var app, bcrypt, cookieParser, express, fs, router, serverPassword, session;

  express = require('express');

  fs = require('fs');

  bcrypt = require('bcrypt-nodejs');

  cookieParser = require('cookie-parser');

  session = require('express-session');

  app = express();

  router = express.Router();

  serverPassword = "$2a$10$VzR1yyM7JRgTXMP3MXGSTOf/oQ8kBWHG3HSj5XytBQYr39.UE2etC";

  app.use(cookieParser());

  app.use(session({
    secret: 'whatIsThis?'
  }));

  app.get('/verify', function(req, res) {
    console.log("mekmek");
    req.session.varified = true;
    return res.send("hacked");
  });

  app.get('/', function(req, res) {
    return res.redirect('/client/index.html');
  });

  app.use('/client', function(req, res) {
    var options, requestedFile;
    console.log("mekmek");
    if (req.session.varified === true) {
      console.log(req.originalUrl.replace("/client/", ""));
      requestedFile = req.originalUrl.replace("/client/", "");
      options = {
        root: __dirname.replace("server/js", "") + "client"
      };
      return res.sendFile(requestedFile, options, function(err) {
        if (err) {
          return console.log(err);
        } else {
          return console.log("sent");
        }
      });
    } else {
      req.session.varified = false;
      return res.redirect('/loginPage');
    }
  });

  app.use("/loginPage", express["static"](__dirname.replace("server/js", "") + "loginPage"));

  app.listen('5555');

  console.log('Magic happens on port 5555');

}).call(this);
